# Be sure to restart your server when you modify this file.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    soundclould_client_id    : d8e3e9334f0a15d5eeee12b1b0b259dd
    soundcloud_client_secret : 9d4bbe1a90a00bf5250e282b192919b3
    box_api_key              : 1pa9m5bxttlar1d4qv0akgoj71an30c4
    box_client_id            : 1pa9m5bxttlar1d4qv0akgoj71an30c4
    box_client_secret        : JRCbGQIaDVTTartXzWUcOlbQ4PjtznI3

test:
    soundclould_client_id    : d8e3e9334f0a15d5eeee12b1b0b259dd
    soundcloud_client_secret : 9d4bbe1a90a00bf5250e282b192919b3
    box_api_key              : 1pa9m5bxttlar1d4qv0akgoj71an30c4
    box_client_id            : 1pa9m5bxttlar1d4qv0akgoj71an30c4
    box_client_secret        : JRCbGQIaDVTTartXzWUcOlbQ4PjtznI3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
    soundclould_client_id    : <%= ENV["SOUNDCLOUD_CLIENT_ID"] %>
    soundcloud_client_secret : <%= ENV["SOUNDCLOUD_CLIENT_SECRET"] %>
    box_api_key              : <%= ENV["BOX_NET_API_KEY"] %>
    box_client_id            : <%= ENV["BOX_NET_CLIENT_ID"] %>
    box_client_secret        : <%= ENV["BOX_NET_CLIENT_SECRET"] %>
